.gitignore, pom.xml, src/main/java/com/clouway/links/Counter.java, src/test/java/com/clouway/links/CounterTest.java, web/WEB-INF/web.xml
Servlet that counts the number of times specific link has been clicked.
=> Three links

.gitignore, pom.xml, src/main/java/com/clouway/radio/buttons/First.java, src/main/java/com/clouway/radio/buttons/RadioMenu.java, src/main/java/com/clouway/radio/buttons/Second.java, src/main/java/com/clouway/radio/buttons/Third.java, src/test/java/com/clouway/radio/buttons/RadioMenuTest.java, web/WEB-INF/web.xml
servlet with 3 radio buttons each lead to a different servlet, which prints message only when opened the first time.
=> Radio buttons

pom.xml, src/com/clouway/adapter/server/jetty/Jetty.java, src/com/clouway/templates/HtmlHelper.java, src/com/clouway/webapp/pages/Demo.java, src/com/clouway/webapp/pages/FirstPageServlet.java, src/com/clouway/webapp/pages/SecondPageServlet.java, src/com/clouway/webapp/pages/ServletDispatcher.java, src/com/clouway/webapp/pages/ServletDisplay.java, src/com/clouway/webapp/pages/ThirdPageServlet.java, test/com/clouway/webapp/FirstPageServletTest.java, test/com/clouway/webapp/HtmlHelperTest.java, test/com/clouway/webapp/SecondPageServletTest.java, test/com/clouway/webapp/ServletDispatcherTest.java, test/com/clouway/webapp/ServletDisplayTest.java, test/com/clouway/webapp/ThirdPageServletTest.java, test/com/clouway/webapp/testFile.txt, web/WEB-INF/first.html, web/WEB-INF/second.html, web/WEB-INF/third.html
Here i have solved the second task: three pages send request to one servlet that recognize from which page is send request and redirect the another page that display it's name.
First page:
Display:
I have test only for first page because the three are the same!
=> Servlet Request Recognizer

src/main/java/com/clouway/bank/core/AccountRepository.java, src/main/java/com/clouway/bank/core/Amount.java, src/main/java/com/clouway/bank/core/TransactionValidator.java, src/main/java/com/clouway/bank/http/BankEventListener.java, src/main/java/com/clouway/bank/http/WithdrawServlet.java, src/main/java/com/clouway/bank/persistent/PersistentAccountRepository.java, src/main/java/com/clouway/bank/validation/BankTransactionValidator.java, src/test/java/com/clouway/bank/BankOperationsTest.java, src/test/java/com/clouway/bank/http/WithdrawServletTest.java, src/test/java/com/clouway/bank/persistent/PersistentAccountTest.java, src/test/java/com/clouway/bank/validation/BankTransactionValidatorTest.java, src/test/java/com/clouway/utility/TemplateSupplementationTest.java, web/WEB-INF/pages/Withdraw.html
Request is sent to WithdrawServlet it uses persistent class which validates the amount of funds, if its valid it withdraws the currency, if it is not it throws an exception, the message of which is displayed to the user(the html itself also validates the amount).
=> Bank withdraw

src/main/java/com/clouway/bank/core/AccountRepository.java, src/main/java/com/clouway/bank/core/TransactionException.java, src/main/java/com/clouway/bank/core/UserException.java, src/main/java/com/clouway/bank/core/ValidationException.java, src/main/java/com/clouway/bank/http/BankEventListener.java, src/main/java/com/clouway/bank/http/ConnectionFilter.java, src/main/java/com/clouway/bank/http/DepositServlet.java, src/main/java/com/clouway/bank/http/HttprequestErrorReporter.java, src/main/java/com/clouway/bank/http/WithdrawServlet.java, src/main/java/com/clouway/bank/persistent/PersistentAccountRepository.java, src/main/java/com/clouway/bank/validation/BankTransactionValidator.java, src/main/java/com/clouway/utility/BracketsTemplate.java, src/main/java/com/clouway/utility/FileReader.java, src/main/java/com/clouway/utility/Reader.java, src/main/java/com/clouway/utility/Template.java, src/test/java/com/clouway/bank/BankOperationsTest.java, src/test/java/com/clouway/bank/http/DepositServletTest.java, src/test/java/com/clouway/bank/http/WithdrawServletTest.java, src/test/java/com/clouway/bank/validation/BankTransactionValidatorTest.java, src/test/java/com/clouway/utility/FileReaderTest.java, src/test/java/com/clouway/utility/TemplateSupplementationTest.java, src/test/java/com/clouway/utility/test.txt, src/test/java/com/clouway/utility/test2.txt, web/WEB-INF/pages/Deposit.html, web/WEB-INF/pages/ErrorPage.html, web/WEB-INF/pages/Withdraw.html
Handling exceptions with a filter(HttpReporterFilter) printing messages to the ErrorPage.html
regex validating whole numbers, validating the withdraw for balance having enough money
extracted the reading of the html
=> Bank reporter

.gitignore, src/main/java/com/clouway/bank/core/Amount.java, src/main/java/com/clouway/bank/core/UserRepository.java, src/main/java/com/clouway/bank/http/BankEventListener.java, src/main/java/com/clouway/bank/http/DepositServlet.java, src/main/java/com/clouway/bank/http/Jetty.java, src/main/java/com/clouway/bank/http/RegistrationController.java, src/main/java/com/clouway/bank/http/RegistrationPage.java, src/main/java/com/clouway/bank/http/WithdrawServlet.java, src/main/java/com/clouway/bank/persistent/PersistentAccountRepository.java, src/main/java/com/clouway/bank/persistent/PersistentUserRepository.java, src/test/java/com/clouway/bank/BankOperationsTest.java, src/test/java/com/clouway/bank/http/DepositServletTest.java, src/test/java/com/clouway/bank/http/RegistrationControllerTest.java, src/test/java/com/clouway/bank/http/WithdrawServletTest.java, src/test/java/com/clouway/bank/persistent/PersistentAccountTest.java, src/test/java/com/clouway/bank/persistent/PersistentUserRepositoryTest.java, src/test/java/com/clouway/bank/validation/BankTransactionValidatorTest.java, web/WEB-INF/pages/Deposit.html, web/WEB-INF/pages/Withdraw.html
moved validation to the servlets.
=> bank validation

src/main/java/com/clouway/bank/core/SessionRepository.java, src/main/java/com/clouway/bank/http/BankEventListener.java, src/main/java/com/clouway/bank/http/LogoutController.java, src/main/java/com/clouway/bank/persistent/PersistentSessionRepository.java, src/test/java/com/clouway/bank/http/LogoutControllerTest.java, src/test/java/com/clouway/bank/http/validation/LogoutControllerTest.java, src/test/java/com/clouway/bank/persistent/PersistentSessionRepositoryTest.java, web/WEB-INF/pages/Home.html
Logout controller which removes the session from the repository and the cookie.
=> Bank Logout

src/main/java/com/clouway/bank/core/SessionRepository.java, src/main/java/com/clouway/bank/http/BankEventListener.java, src/main/java/com/clouway/bank/http/HomePage.java, src/main/java/com/clouway/bank/persistent/PersistentSessionRepository.java, src/test/java/com/clouway/bank/http/HomePageTest.java, src/test/java/com/clouway/bank/persistent/PersistentSessionRepositoryTest.java, src/test/java/com/clouway/bank/utils/SessionRepositoryUtility.java, web/WEB-INF/pages/Deposit.html, web/WEB-INF/pages/Home.html, web/WEB-INF/pages/Login.html, web/WEB-INF/pages/Withdraw.html
Made a active sessions counting,the result of which is displayed in the HomePage, when the users opens it.
Also added bootstrap menu to the home page and the other pages.
=> Logged users counting

schemas/schema.sql, src/main/java/com/clouway/bank/core/AccountHistoryPager.java, src/main/java/com/clouway/bank/core/AccountHistoryRepository.java, src/main/java/com/clouway/bank/core/AccountPager.java, src/main/java/com/clouway/bank/core/AccountRecord.java, src/main/java/com/clouway/bank/http/AccountHistoryPage.java, src/main/java/com/clouway/bank/http/BankEventListener.java, src/main/java/com/clouway/bank/persistent/PersistentAccountHistoryRepository.java, src/main/java/com/clouway/utility/BracketsTemplate.java, src/main/java/com/clouway/utility/Cell.java, src/main/java/com/clouway/utility/HtmlTableBuilder.java, src/main/java/com/clouway/utility/HtmlTableCell.java, src/main/java/com/clouway/utility/RowBuilder.java, src/main/java/com/clouway/utility/TableBuilder.java, src/main/java/com/clouway/utility/Template.java, src/test/java/com/clouway/bank/AccountHistoryPagerTest.java, src/test/java/com/clouway/bank/http/AccountHistoryPageTest.java, src/test/java/com/clouway/bank/persistent/PersistentAccountHistoryRepositoryTest.java, src/test/java/com/clouway/utility/HtmlTableBuilderTest.java, src/test/java/com/clouway/utility/TemplateSupplementationTest.java, web/WEB-INF/pages/AccountHistory.html, web/WEB-INF/pages/Login.html, web/WEB-INF/pages/Register.html
History with the users operations, devided in pages of twenty.
=> Bank: history of user account operations

src/main/java/com/clouway/bank/core/Amount.java, src/main/java/com/clouway/bank/core/DataStore.java, src/main/java/com/clouway/bank/core/RowFetcher.java, src/main/java/com/clouway/bank/http/AccountHistoryPage.java, src/main/java/com/clouway/bank/http/BankEventListener.java, src/main/java/com/clouway/bank/persistent/DatabaseHelper.java, src/main/java/com/clouway/bank/persistent/PersistentAccountHistoryRepository.java, src/main/java/com/clouway/bank/persistent/PersistentAccountRepository.java, src/main/java/com/clouway/bank/persistent/PersistentSessionRepository.java, src/main/java/com/clouway/bank/persistent/PersistentUserRepository.java, src/test/java/com/clouway/bank/http/AccountHistoryPageTest.java, src/test/java/com/clouway/bank/http/RegistrationControllerTest.java, src/test/java/com/clouway/bank/persistent/DatabaseHelperTest.java, src/test/java/com/clouway/bank/persistent/PersistentAccountHistoryRepositoryTest.java, src/test/java/com/clouway/bank/persistent/PersistentAccountRepositoryTest.java, src/test/java/com/clouway/bank/persistent/PersistentSessionRepositoryTest.java, src/test/java/com/clouway/bank/persistent/PersistentUserRepositoryTest.java, web/WEB-INF/pages/AccountHistory.html
I have implemented a basic DataStore, and replaced all the complex code in the repositories, with one using this DataStore
=> Bank data store

task4/src/main/java/com/clouway/bankrepository/PersistentCustomerRepository.java, task4/src/main/java/com/clouway/core/CustomerRepository.java, task4/src/main/java/com/clouway/http/servlets/LoginPageServlet.java, task4/src/main/java/com/clouway/http/servlets/TransactionPageServlet.java, task4/src/main/resources/transaction.html, task4/src/main/test/com/clouway/repository/PersistentCustomerRepositoryTest.java, task4/src/main/test/com/clouway/repository/PersistentSessionRepositoryTest.java, task4/src/main/test/com/clouway/servlets/TransactionPageServletTest.java, task4/src/main/webapp/WEB-INF/web.xml
Transaction functionality for the bank ready for review!
Fixes #69
=> bank: transaction

.gitignore, pom.xml
Added a maven pom.xml which adds dependencies and basic build lifecycle to build milev's bank.
=> bank: build bank using maven

README.md, pom.xml, src/main/java/com/clouway/App.java, src/main/java/com/clouway/http/servlets/IndexPageServlet.java, src/main/java/com/clouway/http/servlets/LoginPageServlet.java, src/main/java/com/clouway/persistent/adapter/jdbc/ConnectionProvider.java, src/main/java/com/clouway/persistent/datastore/DataStore.java, src/test/java/com/clouway/persistent/adapter/jdbc/PersistentAccountRepositoryTest.java
Database configuration is now performed through the environment variables instead of hardcoding it in the code.
This makes environment more flexible and allows each developer to use it's own database.
=> bank: make persistence to use environment configuration

src/main/java/com/clouway/core/ServletResponseWriter.java, src/main/java/com/clouway/http/servlets/HtmlServletResponseWriter.java, src/main/java/com/clouway/http/servlets/IndexPageServlet.java, src/main/java/com/clouway/http/servlets/LoginPageServlet.java, src/test/java/com/clouway/http/servlets/IndexPageServletTest.java, src/test/java/com/clouway/http/servlets/LoginPageServletTest.java
The logic for writing of the HTTP response is now delegated to a separate ServletResponseWriter which is now responsible for writing of the response.
=> bank: improve page rendering

src/main/java/com/clouway/http/servlets/IndexPageServlet.java, src/main/java/com/clouway/http/servlets/LoginPageServlet.java
init() methods from Servlets are now replaced with Constructor calls which are looking much simpler that it was.
=> bank: cleanup init methods from Index and Login servlets

src/main/java/com/clouway/http/servlets/HtmlServletPageRenderer.java
Few minor renames are now performed to clean role separations in the renderer.
=> bank: few name improvements in HtmlServletPageRenderer

pom.xml, src/main/java/com/clouway/core/ConnectionPool.java, src/main/java/com/clouway/persistent/adapter/jdbc/ConnectionProvider.java
Added a connection pool to the database, that way we won't have to create new connection for each request. This will allow us the reduce the latency. It is a single connection pool that uses 3 connections to the DB that are reused
Fixes #95
=> bank: connection pool

README.md
Added link with build status in README.md
=> bank/docs: add build status in README.md

src/main/java/com/clouway/http/server/JettyServer.java, src/main/java/com/clouway/http/servlets/HomeServlet.java, src/main/webapp/WEB-INF/web.xml
Jetty server is now starting properly using src/main/webapp and War method.
Added and a simple HomeServlet which is using TBD context to show that app is serving and home screen.
Fixes #94
=> bank: start jetty server properly

src/test/java/com/clouway/http/servlets/LoginPageServletTest.java, src/test/java/com/clouway/http/servlets/RegistrationPageServletTest.java
Fixed broken tests from last commit.
=> bank: fixed broken tests from last commit

src/main/java/com/clouway/core/Account.java, src/main/java/com/clouway/core/AccountRepository.java, src/main/java/com/clouway/http/servlets/RegistrationPageServlet.java, src/main/java/com/clouway/http/servlets/TransactionPageServlet.java, src/main/java/com/clouway/persistent/adapter/jdbc/PersistentAccountRepository.java, src/main/java/com/clouway/persistent/datastore/DataStore.java, src/main/java/com/clouway/persistent/datastore/TransactionCall.java, src/main/resources/com/clouway/http/servlets/transaction.html, src/main/webapp/WEB-INF/web.xml, src/test/java/com/clouway/http/servlets/AccountPageServletTest.java, src/test/java/com/clouway/http/servlets/LoginPageServletTest.java, src/test/java/com/clouway/http/servlets/RegistrationPageServletTest.java, src/test/java/com/clouway/http/servlets/TransactionPageServletTest.java, src/test/java/com/clouway/persistent/adapter/jdbc/PersistentAccountRepositoryTest.java
Added deposit and withdraw functionality, so that users can operate with their money . Username is hardcoded because there's still no session to get it from.
Fixes #75 
Fixes #71
=> bank: deposit and withdraw functionality

src/main/java/com/clouway/core/DailyActivityRepository.java, src/main/java/com/clouway/core/HistoryRepository.java, src/main/java/com/clouway/http/servlets/AccountPageServlet.java, src/main/java/com/clouway/persistent/adapter/jdbc/PersistentDailyActivityRepository.java, src/main/java/com/clouway/persistent/adapter/jdbc/PersistentHistoryRepository.java, src/main/java/com/clouway/persistent/datastore/DataStore.java, src/test/java/com/clouway/http/servlets/AccountPageServletTest.java, src/test/java/com/clouway/persistent/adapter/jdbc/PersistentDailyActivityRepositoryTest.java, src/test/java/com/clouway/persistent/adapter/jdbc/PersistentHistoryRepositoryTest.java
Added statistics about the number of deposits and withdraws for the current day.They are displayed on the home page of the bank.
Fixes #57
=> bank: collecting statistics of the bank activity
